### PR TITLE
Create 2022-10-25-how-to-monitor-server-load.md

### PR DESCRIPTION
**Pull request by DShreve2**

### CODE REVIEW

**Review by shyamvalsan — APPROVED** [review]

**Comment by shyamvalsan** [comment]
@DShreve2 made some minor edits

**Review by andrewm4894 — APPROVED** [review]

**Comment by andrewm4894** [comment]
Wait it mentions a video walkthrough but I don't see one

**Comment by andrewm4894** [comment]
File need to be an .mdx for the video player

**Comment by andrewm4894** [comment]
Fixed video in this commit https://github.com/netdata/blog/pull/88/commits/092e018930f7bad9009a56a2d5a4f2351de6a857

**Review by andrewm4894 — APPROVED** [review]

**Review by andrewm4894 — APPROVED** [review]

**Comment by andrewm4894** [comment]
@DShreve2 that's the wrong video

**Comment by andrewm4894** [comment]
https://youtu.be/raKbfYi6cbg

So raKbfYi6cbg is video id you want

**Review by andrewm4894 — APPROVED** [review]

**Pull request merged**
