### PR TITLE
Update the navigation in the top bar

### PR DESCRIPTION
**Pull request by Ancairon**
After some discussion we decided that the navigation in Learn should be:

NETDATA logo -> link to main site
Learn -> home page of Learn
Browse Tags -> give the user a way to browse the tags of the blog
Community -> link to community
App -> link to the app

@DShreve2 @andrewm4894 I couldn't get the github logo we got on Learn to render, but I saw from [here](https://github.com/logos) we don't have the proper up-to-date logo, so maybe we could use a new one they got the light version too, so let me know if you want me to change it in both the navbars (or if we want a text based message "Visit our Github!" or something)!

### CODE REVIEW

**Comment by DShreve2** [comment]
> After some discussion we decided that the navigation in Learn should be:
> 
> NETDATA logo -> link to main site Learn -> home page of Learn Browse Tags -> give the user a way to browse the tags of the blog Community -> link to community App -> link to the app
> 
> @DShreve2 @andrewm4894 I couldn't get the github logo we got on Learn to render, but I saw from [here](https://github.com/logos) we don't have the proper up-to-date logo, so maybe we could use a new one they got the light version too, so let me know if you want me to change it in both the navbars (or if we want a text based message "Visit our Github!" or something)!

I think we should change to the github-approved image unless we find it breaks our brand.

**Comment by andrewm4894** [comment]
It feels strange to click the netdata logo and jump to a different site. Expected behavior I think is logo gets you to homepage of site you on. Could just be I'm used to that though.

**Comment by Ancairon** [comment]
> It feels strange to click the netdata logo and jump to a different site. Expected behavior I think is logo gets you to homepage of site you on. Could just be I'm used to that though. 

Yeah, I got the same vibe, we could just add a main website link then, and this way we fix the issue you mention above

**Comment by DShreve2** [comment]
> > It feels strange to click the netdata logo and jump to a different site. Expected behavior I think is logo gets you to homepage of site you on. Could just be I'm used to that though.
> 
> Yeah, I got the same vibe, we could just add a main website link then, and this way we fix the issue you mention above

This works for me. If it feels weird to you two, it'll feel weird to most of our users.

**Review by DShreve2 — APPROVED** [review]

**Comment by Ancairon** [comment]
@DShreve2 @andrewm4894 I added the new suggestions, home menu goes to home, website link added, github link added.

**Comment by Ancairon** [comment]
@andrewm4894 I think this is ready, we merged https://github.com/netdata/learn/pull/1213 today as well.

**Pull request merged**
