### PR TITLE
Dev google search

### PR DESCRIPTION
**Pull request by andrewm4894**
a clean branch to work on adding google search box to navbar

### CODE REVIEW

**Comment by andrewm4894** [comment]
It looks like after the 3 commits above the deploy preview is actually showing the seach box now. 

image

And looks like it is just messing up formatting of the navbar a bit

**Comment by andrewm4894** [comment]
last commit was to try add some css to make it fit - still looks ugly (but progress maybe :) ):

image

**Comment by andrewm4894** [comment]
maybe getting closer - literally no idea what im doing 

image

**Comment by Ancairon** [comment]
I tried it locally, got it to render once, and the results made the top bar huge... No luck getting it to render again so far

**Comment by andrewm4894** [comment]
https://user-images.githubusercontent.com/2178292/199236650-5ba92ab4-617a-496d-9635-5518d95f97fb.mp4

**Comment by andrewm4894** [comment]
@christophidesp hey - this is the branch and pr where i was playing around. 

this is the SO question with an alternative approach where we just would ["swizzle"](https://docusaurus.io/docs/swizzling) ("customize") instead the `NavbarContent` function which maybe would be a more cleaner solution than in here where i am just trying to use a [html item](https://docusaurus.io/docs/api/themes/configuration#navbar-with-custom-html) in navbar. 

https://stackoverflow.com/questions/74227662/how-to-use-google-search-on-a-docusaruas-blog/74228495#74228495

**Comment by andrewm4894** [comment]
love it @christophidesp !

one small thing on my laptop is these arrows? 

image

**Comment by andrewm4894** [comment]
@christophidesp have you any idea maybe why the search box seems to need an f5 to render when you move from one page to another? See my video above. Struggling to see why it might be, assuming maybe something related to static sites maybe.

**Comment by andrewm4894** [comment]
closing to work here instead https://github.com/netdata/blog/pull/194

**Pull request closed without merging**
